// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2w1mUYz5D3UwxBlqWR8wdoQ95ucEw9Rw',
    appId: '1:76950093069:web:37b4c96ce69d02c8604444',
    messagingSenderId: '76950093069',
    projectId: 'new-app-d89c5',
    authDomain: 'new-app-d89c5.firebaseapp.com',
    storageBucket: 'new-app-d89c5.appspot.com',
    measurementId: 'G-DMGDH45Z63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKCNvhhBLE6t4jWxotnRi05mQJGvHjQI',
    appId: '1:76950093069:android:14f40da3f356d5c7604444',
    messagingSenderId: '76950093069',
    projectId: 'new-app-d89c5',
    storageBucket: 'new-app-d89c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeR1AXnyTuoy_TJeyg0IEux1v-A7yAog',
    appId: '1:76950093069:ios:26926f99838c2731604444',
    messagingSenderId: '76950093069',
    projectId: 'new-app-d89c5',
    storageBucket: 'new-app-d89c5.appspot.com',
    iosClientId: '76950093069-9cvsvrunlmvkr0tenc2cel51qbsiv5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHeR1AXnyTuoy_TJeyg0IEux1v-A7yAog',
    appId: '1:76950093069:ios:26926f99838c2731604444',
    messagingSenderId: '76950093069',
    projectId: 'new-app-d89c5',
    storageBucket: 'new-app-d89c5.appspot.com',
    iosClientId: '76950093069-9cvsvrunlmvkr0tenc2cel51qbsiv5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );
}
